name: Sync World Cup Data
on:
  schedule:
    # This runs every 4 hours
    - cron: "*/30 * * * *"
  workflow_dispatch: # Allows you to run it manually from GitHub for testing

jobs:
  ping_api:
    runs-on: ubuntu-latest
    steps:
      - name: Hit Sync Endpoints
        run: |
          curl -X GET "https://www.wcp-2026.com/api/matches" \
          -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}"

          curl -X GET "https://www.wcp-2026.com/api/current-standings" \
          -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}"
